### ISSUE TITLE
Add assigns like live_view

### ISSUE THREAD

**Issue by RodolfoSilva** [launchscout/live_state#19]
I was wondering if we can add assignments to live_state like LiveView, to send only the assigned state to the front end and also have states that only stay on the server without being sent over the socket, instead of always sending all state to the front .

I'm wanting something more explicit. I'm developing an Server Driven UI with Flutter, and I'm doing it purely with Channel. But I would like to migrate to live_state as it is more mature and well documented. The only thing it lacks this explicit assignment.

**Comment by superchris** [comment]
Hey Rodolfo, you should be able to do this now in LiveState by using different arity versions of the LiveState callbacks. `init`, `handle_event` and so forth all have versions that accept the socket as an additional argument. This will allow you to add socket assigns to set things on state that aren't pushed to the front end. You can find an example in the live_state code in `test/support/socket_channel.ex`. Let me know if this gets you what you need.

**Comment by RodolfoSilva** [comment]
Thanks @superchris, I'll check :D.
