### ISSUE TITLE
Docs should include LiveState.Encoder implementation

### ISSUE THREAD

**Issue by enoonan** [launchscout/live_state#25]
Hi LaunchScout!

I've been using LiveState and ran into an issue where I couldn't figure out why my `Jason.Encoder` implementations for various structs weren't getting called, and errors were ensuing. The README says anything that gets passed into state [must have a `Jason.Encoder` implementation](https://github.com/launchscout/live_state/blob/9664f81c1eb69029b5ab327e6f4c874b600531dc/README.md?plain=1#L69).

After digging through the source a bit I realized what I actually need is to [implement the `LiveState.Encoder` protocol](https://github.com/launchscout/live_state/blob/9664f81c1eb69029b5ab327e6f4c874b600531dc/lib/live_state/message_builder.ex#L18). I currently have both encoders implemented for my structs, though I'm not sure I still need the `Jason` one.

This leads me to two possible conclusions:

1. I'm doing it wrong
2. The docs could use an update

I enjoy writing docs and would be happy to update them if indeed I am on the right track. Otherwise - any thoughts as to what I could be doing wrong? Thanks for a great library -

~Eileen

**Comment by superchris** [comment]
Hey Eileen! Thanks so much for checking out LiveState. I'll see if I can dig into this tomorrow and see what's up to make sure the issue isn't 3. Chris made a boo boo :) 

And yes, I would love and welcome documentation PRS :)

**Comment by superchris** [comment]
Yep, I think the documentation is now out of date. I've now made sending json patches the default rather than having to opt-in, and with that I needed to add the `LiveState.Encoder` protocol. The good news is that it should "just work" in most cases and has a default implementation that will do some helpful things like drop the `__meta__` from Ecto schemas. I'll update the docs

**Comment by superchris** [comment]
Added a description of the serialization/encoding process to the README, but will be happy to accept any documentation improvements as PRs :)

**Comment by enoonan** [comment]
Thanks so much! Next time I see something I'll send a PR. Great library!
